#!/bin/sh
# InfraView — one-command installer (server stack: backend + frontend + agent)
#
# Quick start (local, http://<this-host>):
#   curl -fsSL https://raw.githubusercontent.com/TimHasenkamp/infraview-osp/main/install.sh | sh
#
# With a domain (automatic HTTPS via Caddy + Let's Encrypt):
#   curl -fsSL .../install.sh | DOMAIN=monitor.example.com sh
#
# Everything runs behind a Caddy reverse proxy so the dashboard, API and
# WebSocket share one origin — no extra configuration needed for live updates.
#
# Options (environment variables):
#   DOMAIN=...           Serve on this domain with automatic HTTPS (ports 80+443).
#   HTTP_PORT=8088       Host port for local (no-domain) mode. Default: 80.
#   INSTALL_DIR=...      Where to write config. Default: ./infraview (or the repo
#                        root when BUILD=1).
#   BUILD=1              Build images from the current source checkout instead of
#                        pulling pre-built images from GHCR.
#   IMAGE_TAG=latest     Image tag to pull in GHCR mode.
#   AGENT_ID=...         Agent display id for the bundled agent. Default: hostname.
#   NO_START=1           Generate the config but don't start the stack (review first).

set -eu

REPO="ghcr.io/timhasenkamp/infraview-osp"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()  { printf "${GREEN}[infraview]${NC} %s\n" "$1"; }
warn()  { printf "${YELLOW}[infraview]${NC} %s\n" "$1"; }
error() { printf "${RED}[infraview]${NC} %s\n" "$1" >&2; exit 1; }

# ── Config from environment ──────────────────────────────────────────────────
DOMAIN="${DOMAIN:-}"
HTTP_PORT="${HTTP_PORT:-80}"
BUILD="${BUILD:-0}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
AGENT_ID="${AGENT_ID:-$(hostname 2>/dev/null || echo infraview-host)}"

if [ "$BUILD" = "1" ]; then
  # Build mode runs from the source checkout; keep generated files out of the way
  # of the committed compose files.
  [ -f Dockerfile.frontend ] && [ -d backend ] && [ -d agent ] || \
    error "BUILD=1 must be run from the repository root (Dockerfile.frontend not found)"
  INSTALL_DIR="${INSTALL_DIR:-.}"
  COMPOSE_FILE="docker-compose.local.yml"
  CADDY_FILE="Caddyfile.local"
else
  INSTALL_DIR="${INSTALL_DIR:-./infraview}"
  COMPOSE_FILE="docker-compose.yml"
  CADDY_FILE="Caddyfile"
fi

ENV_FILE="$INSTALL_DIR/.env"

# ── Preflight ────────────────────────────────────────────────────────────────
preflight() {
  command -v docker >/dev/null 2>&1 || error \
    "Docker is not installed. Install it first: https://docs.docker.com/get-docker/"

  if docker compose version >/dev/null 2>&1; then
    DC="docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
  else
    error "Docker Compose v2 not found. Install the Compose plugin: https://docs.docker.com/compose/install/"
  fi

  if ! docker info >/dev/null 2>&1; then
    error "Cannot talk to the Docker daemon. Is it running, and do you have permission (try sudo)?"
  fi
}

# ── Secrets ──────────────────────────────────────────────────────────────────
gen_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  else
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# Reuse secrets from an existing .env so re-running the installer is safe.
load_or_create_secrets() {
  JWT_SECRET_KEY=""
  AGENT_API_KEY=""
  if [ -f "$ENV_FILE" ]; then
    JWT_SECRET_KEY=$(sed -n 's/^JWT_SECRET_KEY=//p' "$ENV_FILE" | head -n1)
    AGENT_API_KEY=$(sed -n 's/^AGENT_API_KEY=//p' "$ENV_FILE" | head -n1)
  fi
  case "$JWT_SECRET_KEY" in ""|change-me*) JWT_SECRET_KEY=$(gen_hex 32) ;; esac
  case "$AGENT_API_KEY" in ""|change-me*) AGENT_API_KEY=$(gen_hex 16) ;; esac
}

# ── File generation ──────────────────────────────────────────────────────────
# Non-destructive: preserve any other keys already in .env (SMTP, etc.) and only
# set the two managed secrets.
write_env() {
  tmp="${ENV_FILE}.tmp.$$"
  if [ -f "$ENV_FILE" ]; then
    grep -vE '^(JWT_SECRET_KEY|AGENT_API_KEY)=' "$ENV_FILE" > "$tmp" 2>/dev/null || true
  else
    printf '# Generated by install.sh — keep these secret.\n' > "$tmp"
  fi
  printf 'JWT_SECRET_KEY=%s\n' "$JWT_SECRET_KEY" >> "$tmp"
  printf 'AGENT_API_KEY=%s\n' "$AGENT_API_KEY" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

write_caddyfile() {
  if [ -n "$DOMAIN" ]; then
    site="$DOMAIN"
  else
    site=":80"
  fi
  cat > "$INSTALL_DIR/$CADDY_FILE" <<EOF
${site} {
	handle /api/* {
		reverse_proxy backend:8000
	}
	handle /ws/* {
		reverse_proxy backend:8000
	}
	handle {
		reverse_proxy frontend:3000
	}
}
EOF
}

# Emit either a GHCR image ref or a build block for a service.
service_image() {
  svc="$1"; ctx="$2"; dockerfile="$3"
  if [ "$BUILD" = "1" ]; then
    printf '    build:\n      context: %s\n' "$ctx"
    if [ -n "$dockerfile" ]; then
      printf '      dockerfile: %s\n' "$dockerfile"
    fi
  else
    printf '    image: %s/%s:%s\n' "$REPO" "$svc" "$IMAGE_TAG"
  fi
}

write_compose() {
  if [ -n "$DOMAIN" ]; then
    ports="      - \"80:80\"
      - \"443:443\""
    cors="https://${DOMAIN}"
  else
    ports="      - \"${HTTP_PORT}:80\""
    cors="http://localhost:${HTTP_PORT}"
  fi

  {
    echo "# Generated by install.sh — InfraView behind a Caddy reverse proxy."
    echo "services:"
    echo "  caddy:"
    echo "    image: caddy:2-alpine"
    echo "    restart: unless-stopped"
    echo "    ports:"
    echo "$ports"
    echo "    volumes:"
    echo "      - ./${CADDY_FILE}:/etc/caddy/Caddyfile:ro"
    echo "      - caddy-data:/data"
    echo "      - caddy-config:/config"
    echo "    depends_on:"
    echo "      - frontend"
    echo "      - backend"
    echo ""
    echo "  frontend:"
    service_image frontend "." "Dockerfile.frontend"
    echo "    restart: unless-stopped"
    echo "    environment:"
    echo "      - BACKEND_URL=http://backend:8000"
    echo "    depends_on:"
    echo "      - backend"
    echo ""
    echo "  backend:"
    service_image backend "./backend" ""
    echo "    restart: unless-stopped"
    echo "    environment:"
    echo "      - DATABASE_URL=sqlite+aiosqlite:///data/infraview.db"
    echo "      - JWT_SECRET_KEY=\${JWT_SECRET_KEY:?set in .env}"
    echo "      - AGENT_API_KEY=\${AGENT_API_KEY:?set in .env}"
    echo "      - CORS_ORIGINS=[\"${cors}\"]"
    echo "    volumes:"
    echo "      - backend-data:/app/data"
    echo ""
    echo "  agent:"
    service_image agent "./agent" ""
    echo "    restart: unless-stopped"
    echo "    pid: host"
    echo "    environment:"
    echo "      - INFRAVIEW_BACKEND_URL=ws://backend:8000/ws/agent"
    echo "      - INFRAVIEW_API_KEY=\${AGENT_API_KEY:?set in .env}"
    echo "      - INFRAVIEW_AGENT_ID=${AGENT_ID}"
    echo "      - INFRAVIEW_INTERVAL=5"
    echo "      - HOST_PROC=/host/proc"
    echo "      - COMPOSE_PROJECT_DIR=/host/compose"
    echo "    volumes:"
    echo "      - /var/run/docker.sock:/var/run/docker.sock:ro"
    echo "      - /proc:/host/proc:ro"
    echo "      - /etc/os-release:/host/os-release:ro"
    echo "      - .:/host/compose"
    echo "    depends_on:"
    echo "      - backend"
    echo ""
    echo "volumes:"
    echo "  backend-data:"
    echo "  caddy-data:"
    echo "  caddy-config:"
  } > "$INSTALL_DIR/$COMPOSE_FILE"
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
  printf "${BOLD}InfraView installer${NC}\n"
  preflight

  mkdir -p "$INSTALL_DIR"
  load_or_create_secrets
  write_env
  write_caddyfile
  write_compose
  info "Wrote config to ${INSTALL_DIR}/ (${COMPOSE_FILE}, ${CADDY_FILE}, .env)"

  if [ -n "$DOMAIN" ]; then
    info "Mode: domain — automatic HTTPS for https://${DOMAIN} (ports 80 + 443 must be reachable)"
    url="https://${DOMAIN}"
  else
    info "Mode: local — serving on port ${HTTP_PORT}"
    url="http://localhost:${HTTP_PORT}"
  fi

  if [ "${NO_START:-0}" = "1" ]; then
    warn "NO_START=1 — config written but stack not started."
    printf "Start it with:  (cd %s && %s -f %s up -d%s)\n" \
      "$INSTALL_DIR" "$DC" "$COMPOSE_FILE" "$([ "$BUILD" = "1" ] && echo ' --build')"
    return
  fi

  info "Starting the stack..."
  up_args="up -d"
  if [ "$BUILD" = "1" ]; then
    up_args="up -d --build"
  fi
  # shellcheck disable=SC2086
  ( cd "$INSTALL_DIR" && $DC -f "$COMPOSE_FILE" $up_args )

  printf "\n${GREEN}${BOLD}InfraView is up.${NC}\n"
  printf "  Dashboard:      %s\n" "$url"
  printf "  Admin password: %s\n" "(cd $INSTALL_DIR && $DC logs backend | grep Password)"
  printf "  Add more hosts: run deploy/install-agent.sh on them with\n"
  printf "                  AGENT_API_KEY=%s\n" "$AGENT_API_KEY"
  printf "\nStop with:  (cd %s && %s -f %s down)\n" "$INSTALL_DIR" "$DC" "$COMPOSE_FILE"
}

main "$@"
